config/routes.rb
Rails.application.routes.draw do

  root 'users#welcome'
  
  #Yin Yin Aye 
  get '/workspacecreate',    to: 'users#workspacecreate'
  get '/managemember',    to: 'users#managemember'
  get '/home',    to: 'users#home'
  ##post '/home',    to: 'users#home'
  get  '/welcome',    to: 'users#welcome'
  get  '/memberlist',    to: 'users#memberlist'
  get  '/addmember',    to: 'users#addmember'
  get  '/memberadd',    to: 'users#add'
  ##get  '/remove',    to: 'users#remove'
  delete  '/remove',    to: 'users#remove'
  ##get  '/admin',    to: 'users#admin'
  patch  '/admin',    to: 'users#admin' 
  #20190711
  ##get  '/user',    to: 'users#user'
  patch  '/user',    to: 'users#user' 
  #20190711
  #20190625
  get '/unread',    to: 'users#unread'
  post '/unread',    to: 'users#unread'
  patch '/unread',    to: 'users#unread'
  get '/unreadall',    to: 'users#unreadall'
  patch '/unreadall',    to: 'users#unreadall'
  get '/invite',    to: 'users#invite'
  post '/join',    to: 'users#join'
  #Thu Zin Tun
  get  '/invitesuccess',    to: 'users#invitesuccess'
  post '/invitesuccess',    to: 'users#invitesuccess'
  get  '/memberinvite',    to: 'users#memberinvite' 
  get 'sessions/new'
  get  '/signup',  to: 'muser#new'
  post  '/create',  to: 'muser#create'
  get  '/workspacecreate',  to: 'muser#workspacecreate' 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy' 
  get  '/searchworkspace',    to: 'users#searchworkspace' 
  post  '/searchworkspace',    to: 'muser#search' 
  
  #Aye Aye Mu
  #get  '/searchworkspace',    to: 'users#searchworkspace'
  #get  '/newworkspace',    to: 'users#newworkspace'
  #get  '/channelcreate',    to: 'users#channelcreate'
  #post  '/channelcreate',    to: 'users#channelcreate'
  get  '/member',    to: 'users#member'

  #KMMG
  get '/newworkspace', to: 'sessions#newworkspace'
 # post '/newworkspace', to: 'sessions#newworkspace'
  post  '/workspacecreate',    to: 'sessions#workspacecreate'
  #get  '/workspacecreate',    to: 'sessions#workspacecreate'
  get  '/chchannel',    to: 'channel#chchannel'
  #post  '/chchannel',    to: 'channel#chchannel'
  get  '/createchannel',    to: 'channel#createchannel'
  post  '/createchannel',    to: 'channel#createchannel'

  #chat
  #cna
  get '/channelchat',    to: 'users#channel_chat'
  ##post '/channelchat',    to: 'users#channel_chat'
  get '/dirchat',    to: 'users#dirchat'
  post '/dirchat',    to: 'users#dirchat'
  ##get '/msgsend',    to: 'users#msgsend'
  post '/msgsend',    to: 'users#msgsend'
  get '/mention', to: 'users#mention'
  post '/mention', to: 'users#mention'
  get '/dirmsgsend',    to: 'users#dirmsgsend'
  post '/dirmsgsend',    to: 'users#dirmsgsend'
  get '/dirthread',    to: 'users#dirthread'
  post '/dirthread',    to: 'users#dirthread'
  get '/dirthreadinsert',    to: 'users#dirthread_insert'
  post '/dirthreadinsert',    to: 'users#dirthread_insert'
  get '/channelthread',    to: 'users#channelthread'
  ##post '/channelthread',    to: 'users#channelthread'
  ##get '/channelthreadinsert',    to: 'users#channelthread_insert'
  post '/channelthreadinsert',    to: 'users#channelthread_insert'
  get '/threadselect',    to: 'users#threadselect'
  ##post  '/removechannel',    to: 'users#removechannel'
  delete  '/removechannel',    to: 'users#removechannel'
  
  # direct star
  get '/dirstar',  to: 'users#dirstar_message'
  get '/dirunstar',  to: 'users#dirunstar_message'

  get '/chastar',  to: 'users#chastar_message'
  get '/chaunstar',  to: 'users#chaunstar_message'
 
  get '/star',  to: 'users#star'
  get '/dirdelete', to:'users#dirdelete'
  get '/chadelete', to:'users#chadelete'
  get '/destroy', to:'sessions#destroy'
  delete '/destroy', to:'sessions#destroy'
  
  get '/refresh', to: 'users#refresh'
  
  
  resources :m_channels
  resources :m_users
  resources :account_activations, only: [:edit]
  #resources :t_channel_msg,          only: [:msgsend, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def welcome
    end
    
    def home
        #call list method
        left_panel
    end
    
    #Channel Chat Room
    def channel_chat
        channel_memberlist
        #create session for channel
        mchannel = MChannel.find_by(id:params[:chid])
        channel mchannel
        

        #select all user for mention
        @channeluser = MChannel.select("m_users.id as userid, m_users.user_name").
        joins("join m_users on m_users.id = m_channels.user_id").
        where("m_channels.member=1 and m_channels.id=?",session[:channel_id])
        
        #select corresponding channel messages
        @channel_msg = TChannelMsg.select("m_users.user_name,t_channel_msgs.id, t_channel_msgs.channel_msg, t_channel_msgs.sender_id, t_channel_msgs.created_at").
        joins("join m_users on t_channel_msgs.sender_id = m_users.id").
        where("t_channel_msgs.channel_id = ?", session[:channel_id]).
        order("t_channel_msgs.created_at")

        #update channel message as read after click event
        TChannelUnreadMsg.joins("join t_channel_msgs on t_channel_msgs.id = t_channel_unread_msgs.channel_msg_id").
                    where("t_channel_msgs.channel_id=? and t_channel_unread_msgs.unread_user_id=?",session[:channel_id],session[:muser_id]).update(:unread=>0)
        
        #channel thread count
        @ch_thread_count = []
        for channelmsg in @channel_msg
            @channel_msg_thread = TChannelMsg.select("count(t_channel_msgs.parent_msg_id) as count,t_channel_msgs.parent_msg_id").
                    where("t_channel_msgs.parent_msg_id= ?", channelmsg.id)
            for msg_thread in @channel_msg_thread
                @ch_thread_count << msg_thread
            end
        end
        
        #select star message id for channel
        @chastrid=TChaMsgStr.select("cha_msg_id").where("str_user_id=?",session[:muser_id])

        #create array and push star message id in array
        @t_chastarids = Array.new
        @chastrid.each{|i| @t_chastarids.push(i.cha_msg_id)}
         
        #call list method
        left_panel
    end

    #send message when click send button
    def msgsend
        
        @channel_msg = TChannelMsg.new
        @channel_msg.channel_id = session[:channel_id]
        @channel_msg.sender_id = session[:muser_id]
        @channel_msg.channel_msg = params[:tchamsg][:msg]
        @channel_msg.save
        #current message id
        last_id = TChannelMsg.maximum("id")
        channel_memberlist
        @member_list.each do |memberlist|
            @channel_unread = TChannelUnreadMsg.new
            @channel_unread.channel_msg_id = last_id
            @channel_unread.unread_user_id = memberlist.userid
            @channel_unread.unread = 1
            @channel_unread.save
        end

        #mention
        mention_name = params[:tchamsg][:memtion_name]
        mention_name[0] = ''
        @mention_user = MUser.find_by(user_name: mention_name) 

        unless @mention_user.nil?
            @channel_mention = TMention.new
            mention = MUser.find_by(user_name: mention_name)
            if mention
                @channel_mention.mentioned_user_id = mention.id
                @channel_mention.t_cha_msg_id = last_id
                @channel_mention.save
            end
        end
        
        redirect_back(fallback_location:msgsend_path)
    end
	
	
	
	
	
	
	#mention select
	def mention
        left_panel
        #select mention item
        @mention = TMention.select("t_channel_msgs.channel_msg,m_users.user_name, t_channel_msgs.created_at").
        joins("join t_channel_msgs on t_channel_msgs.id = t_mentions.t_cha_msg_id").
        joins("join m_users on t_channel_msgs.sender_id = m_users.id").
        where("t_mentions.mentioned_user_id =?", session[:muser_id])
    end

    #Channel Thread
    def channelthread
        channel_memberlist
        channelthread= TChannelMsg.find_by(id:params[:channel_thread_id])
        channel_thread channelthread
       
        #select parent message
        @channel_original_msg = TChannelMsg.select("m_users.user_name, t_channel_msgs.channel_msg, t_channel_msgs.created_at").
                            joins("join m_users on m_users.id = t_channel_msgs.sender_id").
                            where("t_channel_msgs.id=?", session[:channel_thread_id])
        #select thread message
        @channel_thread_msg = TChannelMsg.select("m_users.user_name, t_channel_msgs.thread_msg, t_channel_msgs.created_at").
                            joins("join m_users on m_users.id = t_channel_msgs.replier_id").
                            where("t_channel_msgs.parent_msg_id=?", session[:channel_thread_id])

        left_panel
    end
    
    #insert channel thread message
    def channelthread_insert
        @cha_thread = TChannelMsg.new 
        @cha_thread.replier_id = session[:muser_id]
        @cha_thread.parent_msg_id = session[:channel_thread_id]
        @cha_thread.thread_msg = params[:channelthread][:msg]
        @cha_thread.save
        redirect_back(fallback_location:channelthread_path)
    end

    #insert channel star message
    def chastar_message
        if params[:t_cha_star_id]
            @m_cha_msg_str=TChaMsgStr.new(:cha_msg_id =>params[:t_cha_star_id],:str_user_id =>session[:muser_id])
            @m_cha_msg_str.save   
        end
        redirect_back(fallback_location:channelchat_path)
    end

    #destroy channel star message 
    def chaunstar_message
        messageid=params[:t_cha_star_id]
        @ch_msg_strid=TChaMsgStr.select("id").where("cha_msg_id=?", messageid)
        @m_cha_msg_unstar=TChaMsgStr.where(:id => @ch_msg_strid).destroy_all
        redirect_back(fallback_location:channelchat_path)
    end
   
    #Direct Chat Room
    def dirchat
        diruser= MUser.find_by(id:params[:id])
        dir diruser
      
        #select corresponding direct message
        @dir_msg_all = TDirectMsg.select("sender.user_name as s, receiver.user_name as r, t_direct_msgs.id, t_direct_msgs.message, t_direct_msgs.created_at").
                    joins("join m_users as sender on t_direct_msgs.sender_id = sender.id").
                    joins("join m_users as receiver on t_direct_msgs.receiver_id = receiver.id ").
                    where("(t_direct_msgs.sender_id = ?
                    and t_direct_msgs.receiver_id = ?
                    or t_direct_msgs.sender_id = ?
                    and t_direct_msgs.receiver_id = ?)
                    and t_direct_msgs.workspace_id = ?",
                    session[:diruser_id], session[:muser_id], session[:muser_id], session[:diruser_id], session[:workspace_id])
        
        #direct thread count
        @dir_thread_count = []
        for dirmsgread in @dir_msg_all
            @dir_msg_thread = HDirectMsgThread.select("count(h_direct_msg_threads.dir_msg_id) as count,h_direct_msg_threads.dir_msg_id").
                    joins("join t_direct_msgs on h_direct_msg_threads.dir_msg_id = t_direct_msgs.id").
                    where("h_direct_msg_threads.dir_msg_id= ?", dirmsgread.id)
            for msg_thread in @dir_msg_thread
                @dir_thread_count << msg_thread
            end
        end

        #select direct unread message
        @dir_msg_unread = TDirectMsg.select("m_users.user_name, t_direct_msgs.message, t_direct_msgs.created_at").
                    joins("join m_users on t_direct_msgs.sender_id = m_users.id").
                    where("t_direct_msgs.unread=1 and t_direct_msgs.sender_id = ?
                    and t_direct_msgs.receiver_id = ?
                    and t_direct_msgs.workspace_id = ?",
                    session[:diruser_id], session[:muser_id], session[:workspace_id])
        
        @dir_msg_sent = TDirectMsg.select("m_users.user_name, t_direct_msgs.message, t_direct_msgs.created_at").
                    joins("join m_users on t_direct_msgs.sender_id = m_users.id").
                    where("t_direct_msgs.unread=1 and t_direct_msgs.sender_id = ?
                    and t_direct_msgs.receiver_id = ?
                    and t_direct_msgs.workspace_id = ?",
                    session[:muser_id], session[:diruser_id], session[:workspace_id])
        #update direct message as read after click event          
        TDirectMsg.where(:receiver_id=>session[:muser_id], :sender_id=>session[:diruser_id]).update(:unread=>0)
        @dirstrid = TDirMsgStr.select("t_dir_msg_id").where("dir_str_user_id=?",session[:muser_id]) 
        
        #create array and push star message id in array
        @t_dirstarids = Array.new
        @dirstrid.each{|i| @t_dirstarids.push(i.t_dir_msg_id)}
        
        left_panel
    end

    #send message when click send button
    def dirmsgsend
        @dir_msg = TDirectMsg.new
        @dir_msg.sender_id = session[:muser_id]
        @dir_msg.receiver_id = session[:diruser_id]
        @dir_msg.workspace_id = session[:workspace_id]
        @dir_msg.message = params[:dirmsg][:msg]
        @dir_msg.unread = 1
        @dir_msg.save
        #@dir_msg.reload
        redirect_back(fallback_location:dirmsgsend_path)

    end

    #Direct Thread
    def dirthread
        dirthread= TDirectMsg.find_by(id:params[:dir_thread_id])
        thread dirthread

        #select parent message
        @dir_original_msg = TDirectMsg.select("t_direct_msgs.message, m_users.user_name, t_direct_msgs.created_at").
                            joins("join m_users on m_users.id = t_direct_msgs.sender_id").
                            where("t_direct_msgs.id=?", session[:dir_thread_id])
        #select thread message        
        @dir_thread_msg = MUser.select("m_users.user_name, h_direct_msg_threads.thread_msg, h_direct_msg_threads.created_at").
                            joins("join h_direct_msg_threads on m_users.id = h_direct_msg_threads.user_id").
                            joins("join t_direct_msgs on t_direct_msgs.id = h_direct_msg_threads.dir_msg_id").

app/helpers/users_helper.rb
module UsersHelper
    
end

app/views/users/channelthread.html.erb
    <div class="row bd">
        <div class="col-xs-3 col-sm-3 col-md-3 hleft">
            <%= render 'listed/left_panel' %>
        </div>
        <div class="col-xs-9 col-sm-9 col-md-9 member">
           
            <header class="row">
                <div class="col-xs-10 col-sm-10 col-md-10">
                    <h3><%= session[:channel_name] %></h3>
                </div>
            </header>

            <div class="row dframe">
                <br>  
                    <h4><%= "Origin" %> </h4>
                    <ul>
                    <% @channel_original_msg.each do |original|%>
                        <li>
                            <b><%= original.user_name %></b>
                            Posted <%= time_ago_in_words(original.created_at) %> ago.
                            </br>
                            <%= original.channel_msg %>
                        </li>    
                    <% end %>
                    </ul> 
                    
                    <h4><%= "Reply" %></h4> 
                    <ul> 
                    <% @channel_thread_msg.each do |thread|%>
                        <li>
                            <b><%= thread.user_name %></b>
                             <%= (thread.created_at).strftime('%B %d %Y, %l:%M%P') %>
                            </br>
                            <%= thread.thread_msg %>
                        </li>    
                    <% end %>
                    </ul>
                    
                    </ul> 
            </div>
                
            

            <% if @member_list_count.map(&:userid).include? session[:muser_id] %>
            <div class="row footer">
                <%= form_for(:channelthread,url:channelthreadinsert_path) do |f| %>              
                    <%= f.text_area :msg ,class:"col-xs-10 col-sm-10 col-md-10 tatag", autofocus: true %>                   
                    <div class="col-xs-2 col-sm-2 col-md-2">
                        <%= f.submit "Send",class: "btn btn-primary btnsent"%>
                    </div>
                <% end %>
            </div>
            <% else %>
            <div class="row footer">
                <%= form_for(:channelthread,url:channelthreadinsert_path) do |f| %>              
                    <%= f.text_area :msg ,class:"col-xs-10 col-sm-10 col-md-10 tatag"%>                   
                    <div class="col-xs-2 col-sm-2 col-md-2">
                        <%= f.submit "Send",class: "btn btn-primary btnsent disabled"%>
                    </div>
                <% end %>
            </div>
            <% end %>

        </div>
    </div>

app/views/users/dirthread.html.erb
    <div class="row bd">
        <div class="col-xs-3 col-sm-3 col-md-3 hleft">
            <%= render 'listed/left_panel' %>
        </div>
        <div class="col-xs-9 col-sm-9 col-md-9 member">
      
                <header class="row">
                    <div class="col-xs-10 col-sm-10 col-md-10">
                        <h3><%= session[:diruser_name] %></h3>
                    </div>
                </header>

            <div class="row dframe">
                <br>  
                    <h4><%= "Origin" %> </h4> 
                    <ul>
                    <% @dir_original_msg.each do |original|%>
                        <li id="one">
                            <b><%= original.user_name %></b>
                             <%= (original.created_at).strftime('%B %d %Y, %l:%M%P') %> 
                            </br>
                            <%= original.message %>
                        </li>    
                    <% end %>
                    </ul> 
                    <%= "Reply" %>  
                    <ul>
                    <% @dir_thread_msg.each do |thread|%>
                        <li id="one">
                            <b><%= thread.user_name %></b>
                             <%= (thread.created_at).strftime('%B %d %Y, %l:%M%P') %> 
                            </br>
                            <%= thread.thread_msg %>
                        </li>    
                    <% end %>
                    </ul> 
            </div>
                
                
            <div class="row footer">
                    <%= form_for(:dirthread,url:dirthreadinsert_path) do |f| %>
                   
                        <%= f.text_area :msg ,class:"col-xs-10 col-sm-10 col-md-10 tatag", autofocus: true %>                   
                        <div class="col-xs-2 col-sm-2 col-md-2">
                            <%= f.submit "Send",class: "btn btn-primary btnsent"%>
                        </div>
                    <% end %>
            </div>

        </div>
    </div>

app/views/users/managemember.html.erb
    <div class="row bd">
        <div class="col-xs-3 col-sm-3 col-md-3 hleft">
            <%= render 'listed/left_panel' %>
        </div>
        <div class="col-xs-9 col-sm-9 col-md-9 member">

            
                <header class="row">
                    <div class="col-xs-10 col-sm-10 col-md-10">
                        <h3>Manage Member</h3>
                    </div>
                </header>
                <div class="row dframe">
                    <br> 
                        <ul class="col-xs-6 col-sm-6 col-md-6 col-xs-offset-3 col-sm-offset-3 col-md-offset-3">
                            <li><h4><%= label :name, "Name" %></h4> </li><br>
                            <% @muser.each do |muser|%>  
                                <div class="row managemember"> 
                                <li>
                                    <div class="col-xs-3 col-sm-3 col-md-3">
                                       <%= muser.user_name %> 
                                    </div>
                                    <div class="col-xs-3 col-sm-3 col-md-3">
                                        <% if @admin.map(&:user_id).include? muser.id %>            
                                            <%=  "Admin " %>
                                            <div class="btn-group dropright ml-2 mt-5 mm btnadmin">
                                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                                    <span class="caret"></span></button>
                                                    <ul class="dropdown-menu str">
                                                    <%= link_to "Change to User ",user_url(:user_id => muser.id),method: :patch, data: {confirm: "You sure?"} %>
                                            
                                                    </ul>
                                            </div> 
                                        <% else %> 
                                            <%= "User" %> 
                                            <div class="btn-group dropright ml-2 mt-5 mm btnadmin">
                                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                                    <span class="caret"></span></button>
                                                    <ul class="dropdown-menu str">
                                                    <%= link_to "Change to admin ",admin_url(:user_id => muser.id),method: :patch, data: {confirm: "You sure?"} %>
                                                    
                                                    </ul>
                                            </div> 
                                        <% end %> 
                                    </div>                 
                                </li>
                                </div><br>
                            <% end %>
                            </ul>

                   
                </div>
        </div> 
    </div>

app/views/users/memberinvite.html.erb
<% provide(:title, 'MemberInvite') %>

<div class="container memberinvite">
<div>
  <h1>Invite Member to <b><%= session[:workspace_name] %></b></h1>
  <br><br>
</div>
<div class="col-xs-6 col-sm-6 col-md-6 col-xs-offset-3 col-sm-offset-3 col-md-offset-3 text-left">
<%= form_for(:invite,url: invitesuccess_path) do |f| %>
  <%= f.label :EmailAddress1,"Email Address:" %><br>
  <%= f.email_field :email1,value:"name@example.com", class: "form-control" %><br>
  <%= f.label :EmailAddress2,"Email Address:" %><br>
  <%= f.email_field :email2,value:"name@example.com", class: "form-control" %><br>
  <%= f.label :EmailAddress3,"Email Address:" %><br>
  <%= f.email_field :email3,value:"name@example.com", class: "form-control" %><br>
  <%= f.submit "Send Invitations", class:"btn btn-primary btn-lg" %>  
<% end %>  

</div>

app/views/users/memberlist.html.erb
    <div class="row bd">
        <div class="col-xs-3 col-sm-3 col-md-3 hleft">
            <%= render 'listed/left_panel' %>
        </div>
        <div class="col-xs-9 col-sm-9 col-md-9 member">
            
                <header class="row">
                    <div class="col-xs-10 col-sm-10 col-md-10">
                        <h5><%= session[:channel_name]%></h5>
                        <%= link_to "Channel Member List", memberlist_path, class: "mlink" %>
                    </div>
                    
                </header>
                <div class="memberlist1 dframe">  
                        <br>
                        <div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-4 col-xs-offset-3 col-sm-offset-3 col-md-offset-3">
                            <i class="fa fa-user btn btn-success"></i> <%= @member_list.size %> Members
                            </div>
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <%= link_to '',addmember_path, :class=> "fa fa-plus  btn btn-success mlink" %>
                            </div>
                            
                        </div><br>

                        

                        <% @member_list.each do |memberlist|%>
                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-4 col-xs-offset-3 col-sm-offset-3 col-md-offset-3">
                                    <%= memberlist.user_name %>
                                </div>
                                <div class="col-xs-3 col-sm-3 col-md-3">
                                <%= link_to '',remove_url(:user_id => memberlist.userid),method: :delete,data: {confirm: "You sure?"},:class=> "fa fa-minus  btn btn-danger mlink" %>
                                </div>
                            </div><br>
                        <% end %>
                        <div class="row"> 
                            <div class="col-xs-9 col-sm-9 col-md-7 col-xs-offset-3 col-sm-offset-3 col-md-offset-3">                 
                                <%= will_paginate @member_list %> 
                            </div>
                        </div>                       
                </div>   
            

        </div>
    </div>

app/views/users/searchworkspace.html.erb
<% provide(:title, "Search Your WorkSpace") %>

<div class="row searchworkspace">
  <div class="col-xs-8 col-sm-8 col-md-8 col-xs-offset-2 col-sm-offset-2 col-md-offset-2">
  <h1>Search Your WorkSpace</h1>
  <br><br>
  <%= form_for(:workspace, url: searchworkspace_path) do |f| %>
      <%= f.label :workspace_name, "Workspace Name:" %>
      <%= f.text_field :workspace_name, class: "form-control" %>    
      <%= f.label :email, "Email:" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Password:" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Search", class:"btn btn-primary btn-lg btn-block" %>
      <% end %>
  </div>
  </div>

app/views/users/unread.html.erb
    <div class="row bd">
        <div class="col-xs-3 col-sm-3 col-md-3 hleft">
            <%= render 'listed/left_panel' %>
        </div>
        <div class="col-xs-9 col-sm-9 col-md-9 member">
                <header class="row">
                    <div class="col-xs-10 col-sm-10 col-md-10">
                        <h5>All Unreads</h5>
                        <span><%= pluralize((@all_ch_un_count+@all_dir_un_count), "new message") %><span>
                    </div>
                </header>

                <div class="dframe">
                <br>
                <% @channel_id.each do |channelid|%>
                    <div class="row">
                    <% @channel_count.each do |channel|%>
                        <% if channelid.id == channel.channel_id %>
                            <div class="col-xs-6  col-sm-6 col-md-8">
                                <span><b><%= channelid.channel_name  %><i class="fa fa-caret-down"></i></b></span>  
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-4">
                                <span><%= pluralize(channel.count, "message") %><span>
                                <%= link_to "Mark as Read", unread_path(:channel_id => channel.channel_id),method: :patch, :class => "btn btn-primary" %>
                            </div>
                            
                        <% end %>
                    <% end %>
                    </div>
                        <ul>
                            <% @all_channel_unread.each do |ch_unread|%>   
                                <% if channelid.id == ch_unread.channel_id %>
                                    <li>
                                        <span><b><%= ch_unread.user_name%></b></span>
                                        <span><%= (ch_unread.created_at).strftime('%B %d %Y, %l:%M%P') %></span>
                                        </br>
                                        <span><%= ch_unread.channel_msg%></span>
                                    </li>
                                <% end %>
                            <% end %> 
                        </ul>    
                <% end %>  
    
                    <% @dir_count.each do |dir_unread|%>
                        
                        <div class="row">
                            <br>
                            
                            <div class="col-xs-6 col-sm-6 col-md-8 ">
                                <span><b><%= dir_unread.user_name  %><i class="fa fa-caret-down"></i></b></span>
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-4">
                                <span><%= pluralize(dir_unread.count, "message") %><span>
                                <%= link_to "Mark as Read", unread_path(:sender_id => dir_unread.id),method: :patch, :class => "btn btn-primary btnunread" %>
                               
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-xs-10 col-sm-10 col-md-10">
                                <ul>
                                <% @all_dir_unread.each do |all_unread_dir|%>   
                                    <% if (all_unread_dir.sender_id == dir_unread.id)  %>                                       
                                        <li>
                                            <span><b><%= all_unread_dir.user_name  %></b></span>
                                            <span><%= (all_unread_dir.created_at).strftime('%B %d %Y, %l:%M%P')  %></span><br>
                                            <span><%= all_unread_dir.message  %></span>
                                        </li>
                                    <% end %>
                                    <% end %>
                                </ul>
                            </div>
                        </div>
                    
                    <% end %>
                    
                    
                    <% if ((@all_ch_un_count+@all_dir_un_count) != 0)  %>
                    
                        <div class="row footer">
                            <div class="col-xs-6 col-sm-6 col-md-4 col-xs-offset-4 col-sm-offset-4 col-md-offset-4"> 
                                <%= link_to "Mark All Messages Read", unreadall_path,method: :patch, :class => "btn btn-primary btnallunread" %>
                            </div>    
                        </div>
                    <% end %>
                </div>
                
                
                
        </div> 
     
    </div>

app/views/users/welcome.html.erb
<div class="welcome">
  <h3><b>Slack_App</b>
  </h3>
  <p>
  <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>
  </p>
  <br><br>
  <div>
    
    <h1>Welcome to Slack App</h1>

    <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary button1" %>
  </div>
</div>

app/views/users/workspacecreate.html.erb
<div class="container wframe">
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-4 col-xs-offset-2 col-sm-offset-2 col-md-offset-4">
            <%= link_to "WorkSpace Create", newworkspace_path, class: "btn btn-lg btn-primary btnW" %>
        </div>
    </div> 

    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-4 col-xs-offset-2 col-sm-offset-2 col-md-offset-4">
            <%= link_to "Search Your WorkSpace", searchworkspace_path, class: "btn btn-lg btn-primary btnW" %>
        </div>
    </div> 
</div>