config/routes.rb
Rails.application.routes.draw do

  root 'users#welcome'
  
  #Yin Yin Aye 
  get '/workspacecreate',    to: 'users#workspacecreate'
  get '/managemember',    to: 'users#managemember'
  get '/home',    to: 'users#home'
  ##post '/home',    to: 'users#home'
  get  '/welcome',    to: 'users#welcome'
  get  '/memberlist',    to: 'users#memberlist'
  get  '/addmember',    to: 'users#addmember'
  get  '/memberadd',    to: 'users#add'
  ##get  '/remove',    to: 'users#remove'
  delete  '/remove',    to: 'users#remove'
  ##get  '/admin',    to: 'users#admin'
  patch  '/admin',    to: 'users#admin' 
  #20190711
  ##get  '/user',    to: 'users#user'
  patch  '/user',    to: 'users#user' 
  #20190711
  #20190625
  get '/unread',    to: 'users#unread'
  post '/unread',    to: 'users#unread'
  patch '/unread',    to: 'users#unread'
  get '/unreadall',    to: 'users#unreadall'
  patch '/unreadall',    to: 'users#unreadall'
  get '/invite',    to: 'users#invite'
  post '/join',    to: 'users#join'
  #Thu Zin Tun
  get  '/invitesuccess',    to: 'users#invitesuccess'
  post '/invitesuccess',    to: 'users#invitesuccess'
  get  '/memberinvite',    to: 'users#memberinvite' 
  get 'sessions/new'
  get  '/signup',  to: 'muser#new'
  post  '/create',  to: 'muser#create'
  get  '/workspacecreate',  to: 'muser#workspacecreate' 
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy' 
  get  '/searchworkspace',    to: 'users#searchworkspace' 
  post  '/searchworkspace',    to: 'muser#search' 
  
  #Aye Aye Mu
  #get  '/searchworkspace',    to: 'users#searchworkspace'
  #get  '/newworkspace',    to: 'users#newworkspace'
  #get  '/channelcreate',    to: 'users#channelcreate'
  #post  '/channelcreate',    to: 'users#channelcreate'
  get  '/member',    to: 'users#member'

  #KMMG
  get '/newworkspace', to: 'sessions#newworkspace'
 # post '/newworkspace', to: 'sessions#newworkspace'
  post  '/workspacecreate',    to: 'sessions#workspacecreate'
  #get  '/workspacecreate',    to: 'sessions#workspacecreate'
  get  '/chchannel',    to: 'channel#chchannel'
  #post  '/chchannel',    to: 'channel#chchannel'
  get  '/createchannel',    to: 'channel#createchannel'
  post  '/createchannel',    to: 'channel#createchannel'

  #chat
  #cna
  get '/channelchat',    to: 'users#channel_chat'
  ##post '/channelchat',    to: 'users#channel_chat'
  get '/dirchat',    to: 'users#dirchat'
  post '/dirchat',    to: 'users#dirchat'
  ##get '/msgsend',    to: 'users#msgsend'
  post '/msgsend',    to: 'users#msgsend'
  get '/mention', to: 'users#mention'
  post '/mention', to: 'users#mention'
  get '/dirmsgsend',    to: 'users#dirmsgsend'
  post '/dirmsgsend',    to: 'users#dirmsgsend'
  get '/dirthread',    to: 'users#dirthread'
  post '/dirthread',    to: 'users#dirthread'
  get '/dirthreadinsert',    to: 'users#dirthread_insert'
  post '/dirthreadinsert',    to: 'users#dirthread_insert'
  get '/channelthread',    to: 'users#channelthread'
  ##post '/channelthread',    to: 'users#channelthread'
  ##get '/channelthreadinsert',    to: 'users#channelthread_insert'
  post '/channelthreadinsert',    to: 'users#channelthread_insert'
  get '/threadselect',    to: 'users#threadselect'
  ##post  '/removechannel',    to: 'users#removechannel'
  delete  '/removechannel',    to: 'users#removechannel'
  
  # direct star
  get '/dirstar',  to: 'users#dirstar_message'
  get '/dirunstar',  to: 'users#dirunstar_message'

  get '/chastar',  to: 'users#chastar_message'
  get '/chaunstar',  to: 'users#chaunstar_message'
 
  get '/star',  to: 'users#star'
  get '/dirdelete', to:'users#dirdelete'
  get '/chadelete', to:'users#chadelete'
  get '/destroy', to:'sessions#destroy'
  delete '/destroy', to:'sessions#destroy'
  
  get '/refresh', to: 'users#refresh'
  
  
  resources :m_channels
  resources :m_users
  resources :account_activations, only: [:edit]
  #resources :t_channel_msg,          only: [:msgsend, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/listed/_channelrefresh.html.erb
<div class="dframe" id="channelrefresh">
<ul>   
    <% @channel_msg.each do |channelmsg|%>
        <b><%= channelmsg.user_name %></b>
         <%= (channelmsg.created_at).strftime('%B %d %Y, %l:%M%P') %> 
        </br>
        <%= channelmsg.channel_msg %>
        <%= link_to "", channelthread_url(:channel_thread_id => channelmsg.id), :class => "fa fa-envelope" %>
        <% @ch_thread_count.each do |channelmsgthread|%>
            <% if channelmsg.id == channelmsgthread.parent_msg_id %>
                <%= channelmsgthread.count %>
            <% end %>
        <% end %>
        <% if  @t_chastarids.include?channelmsg.id %>    
            <%= link_to "",chaunstar_path(:t_cha_star_id => channelmsg.id), class: "glyphicon glyphicon-star" %>
        <% else %>
            <%= link_to "",chastar_path(:t_cha_star_id => channelmsg.id), class: "glyphicon glyphicon-star-empty" %>
        <% end %>
    
    <%= link_to "Delete", chadelete_path(:t_cha_star_id => channelmsg.id) %>
    <br>
    <% end %>
    
</ul>
</div>

app/views/listed/_left_panel.html.erb
<div class="details" id="refreshdiv">
    <div class="dropdown btnDrop">
        <div class="dropdown-toggle wlink" data-toggle="dropdown">
            <div class="row">
                <div class="col-xs-9 col-sm-9 col-md-10">
                    <span class="wname">
                        <%= session[:workspace_name] %>
                        <br>
                        <%= session[:muser_name] %>
                    </span>
                </div>
                <div class="col-xs-3 col-sm-3 col-md-2"> <b class="caret"></b></div>
            </div>
        </div>
        <ul class="dropdown-menu dropdown-menu-left">
              <% unless @check_admin[0].nil? %>
                <% if @check_admin[0].admin %>
                    <li><%= link_to "Manage Member", managemember_path, class: "alink" %></li>
                <% end %>
              <% end %>
              <li><%= link_to "SignIn other workspace", workspacecreate_path, class: "alink" %></li>
              <li>
                <%= link_to "Sign Out", destroy_url, class: "alink" %>
              </li>
        </ul>
    </div>
    
    <hr>
    
    <%= link_to "Thread", threadselect_path, class: "thread alink" %><br>
    
   
    <%= link_to "Unread", unread_path, class: "unread alink" %>&nbsp
    <% if (@all_ch_un_count+@all_dir_un_count) > 0%>
        <span class="badge bmsg"><%= (@all_ch_un_count+@all_dir_un_count) %></span>
    <% end %>  <br>   
    <div class="row">
        <div class="col-xs-9 col-sm-9 col-md-9">
            <span class="mention">Mention</span>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3">
        <%= link_to "", mention_path, class: "fa fa-at btnms iplus alink" %>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-9 col-sm-9 col-md-9">
            <span class="star">Star</span>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3">
        <%= link_to "", star_url, class: "fa fa-star star btnms iplus alink" %>
        </div>
    </div>

    
 

    <div class="channel">
        <h3>Channel<%= link_to "", chchannel_path, class: "fa fa-plus alink iplus" %></h3>
        <ul class="list-group">

        <% @public_channel.each do |public_channel|%>
            <li class="row">
            <span class="col-xs-9 col-sm-9 col-md-9 name">
            <%=link_to '#'+public_channel.channel_name,channelchat_url(:chid => public_channel.id) ,class: "alink" %>
            <% @channel_count.each do |count|%>
                <% if public_channel.id==count.channel_id%> 
                <span class="badge bmsg"><%= count.count%></span>
                <% end %>
            <% end %>
            </span>
            <span class="col-xs-3 col-sm-3 col-md-3">
            <% unless @check_admin[0].nil? %>
                <% if @check_admin[0].admin %>
                <%= link_to '',removechannel_url(:chid => public_channel.id),method: :delete,data: {confirm: "You sure?"},:class=> "fa fa-minus btnchdel" %>
                <% end %>
            <% end %>
            </span>
            </li>
        <% end %>

        <% @mchannel.each do |mchannel| %>
            <li class="row">
            <span class="col-xs-9 col-sm-9 col-md-9 name">
            <%=link_to '#'+mchannel.channel_name,channelchat_url(:chid => mchannel.id) ,class: "alink" %>
            <% @channel_count.each do |count|%>
                <% if mchannel.id==count.channel_id%> 
                <span class="badge bmsg"><%= count.count%></span>
                <% end %>
            <% end %>
            </span>
            <span class="col-xs-3 col-sm-3 col-md-3">
            <% unless @check_admin[0].nil? %>
                <% if @check_admin[0].admin %>
                <%= link_to '',removechannel_url(:chid => mchannel.id),method: :delete,data: {confirm: "You sure?"},:class=> "fa fa-minus btnchdel" %>
                <% end %>
            <% end %>
            </span>
            </li>
        <% end %>
        </ul>
    </div>

    <div class="memberlist2" id="userlist">
        <h3>Member List</h3>
        <ul class="list-group">
          
        <% @muser.each do |muser|%>
            <li id="usercount" class="mname name">
            <%= link_to muser.user_name, dirchat_url(:id => muser.id), class: "alink"   %>         
                <% @dir_count.each do |count|%>
                    <% if muser.user_name==count.user_name%> 
                    <span class="badge bmsg"><%= count.count%></span>              
                <% end %>
                    
            <% end %>
            </li>
            <% end %>
        </ul>
    </div>

    <div class="dmemberinvite">
        <h3>Member Invite<%= link_to "", memberinvite_path, class: "fa fa-plus alink iplus" %></h3>
    </div>

</div>

app/views/listed/_public_channel.html.erb
<div class="dframe" id="publicchannel">
<ul>   
<% @channel_msg.each do |channelmsg|%>
    <b><%= channelmsg.user_name %></b>
    <%= (channelmsg.created_at).strftime('%B %d %Y, %l:%M%P') %> 
    </br>
    <%= channelmsg.channel_msg %>
    <%= link_to "", channelthread_url(:channel_thread_id => channelmsg.id), :class => "fa fa-envelope" %>
    <% @ch_thread_count.each do |channelmsgthread|%>
        <% if channelmsg.id == channelmsgthread.parent_msg_id %>
            <%= channelmsgthread.count %>
        <% end %>
    <% end %>
    <%= link_to "",chastar_path(:t_cha_star_id => channelmsg.id), class: "glyphicon glyphicon-star-empty" %>
<%= link_to "Delete", "#" %>
<br>
<% end %>
    
</ul>
</div>

app/views/listed/_refreshmsg.html.erb
<div class="dframe"  id="refreshmessage">
                <br>
                <ul>
                    <% @dir_msg_all.each do |dirmsgall|%>
                    <li id="one">
                        <b><%= dirmsgall.s %></b>
                         <%= (dirmsgall.created_at).strftime('%B %d %Y, %l:%M%P') %> 
                        </br>
                        <%= dirmsgall.message %>
                        <%= link_to "", dirthread_url(:dir_thread_id => dirmsgall.id), :class => "fa fa-envelope" %>
                        <% @dir_thread_count.each do |dirmsgthread|%>
                        <% if dirmsgall.id == dirmsgthread.dir_msg_id %>
                        <%= dirmsgthread.count %>
                        <% end %>
                        <% end %>
                        <% if @t_dirstarids.include?dirmsgall.id %>    
                            <%= link_to "",dirunstar_path(:t_dir_star_id => dirmsgall.id), class: "glyphicon glyphicon-star" %>
                            <% else %>
                            <%= link_to "",dirstar_path(:t_dir_star_id => dirmsgall.id), class: "glyphicon glyphicon-star-empty" %>
                        <% end %>
                        <%= link_to "Delete", dirdelete_path(:t_dir_star_id => dirmsgall.id) %>
                    </li>    
                 <% end %>
                </ul>
                
</div> 